### PR TITLE
Replacing undefined with void.

### PR DESCRIPTION
**Pull request by offbeatful**

### CODE REVIEW

**Comment by michael-haberzettel** [comment]
Ok, your solution is better than mine ! I'm going to look too far for the solution. 

Good job.

**Comment by offbeatful** [comment]
Thanks! I am going to release version 3.0 later this week since there are breaking changes.

**Comment by michael-haberzettel** [comment]
Ok, this is also the case for version 2.6.1.

**Comment by michael-haberzettel** [comment]
I look forward to this version :)

**Pull request merged**
